[workspace]
members = ["core", "debug", "rapier"]

[package]
name = "heron"
version = "0.1.0-dev"
authors = ["Jonathan Cornaz"]
edition = "2018"
license = "MIT"
description = "An ergonomic physics API for 2d and 3d bevy games. (powered by rapier)"
repository = "https://github.com/jcornaz/heron/"
keywords = ["game", "gamedev", "physics", "collision", "bevy"]
categories = ["game-development", "simulation"]

[features]
default = ["3d"]
2d = ["heron_rapier/2d", "heron_debug/2d"]
3d = ["heron_rapier/3d", "heron_debug/3d"]
debug = ["heron_debug", "bevy_render"]

[dependencies]
heron_core = { path = "core", version = "^0.1.0-dev" }
heron_rapier = { path = "rapier", version = "^0.1.0-dev" }
heron_debug = { path = "debug", version = "^0.1.0-dev", optional = true }
bevy_app = { git = "https://github.com/bevyengine/bevy.git" }
bevy_render = { git = "https://github.com/bevyengine/bevy.git", optional = true }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = "## [Unreleased]\n\n\n\n## [{{version}}] - {{date}}"
exactly = 1
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...v{{version}}"
exactly = 1
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\[Unreleased\\]: "
replace = "[Unreleased]: ../../compare/v{{version}}...HEAD\n[{{version}}]: "
exactly = 1
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "//! heron = \".+\""
replace = "//! heron = \"{{version}}\""
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "//! heron = \\{ version = \"[0-9a-z\\.-]+\""
replace = "//! heron = { version = \"{{version}}\""
prerelease = true
